### ISSUE TITLE
Husky pre-commit script silently adds all files and could lead to unexpected contents being committed

### ISSUE THREAD

**Issue by josephrignanese** [adobe-rnd/aem-boilerplate-xwalk#43]
Currently the husky pre-commit.mjs executes `git add .`

A slight improvement to this would be modify this to `git add component-models.json component-definition.json component-filters.json` to limit the add to the files which are altered by the precommit hook to avoid accidentally including unrelated changes in the commit.

**Comment by buuhuu** [comment]
Good catch @josephrignanese, merged, thanks.
